def addition(add):
    print("addition is:",add)
def substraction(sub):
    print("substraction is:",sub)
def multiplication(mul):
    print("multiplication is:",mul)
def division(div):
    print("division is:",div)
def percentage(per):
    print("percentage is:",per)